baseURL = "http://suzannejmatthews.github.io/PDC-Unplugged"
languageCode = "en-us"
title = "PDC Unplugged"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[taxonomies]
    tag="tags"

[params]
    author = "Suzanne J. Matthews (CSinParallel)"
    description = "A repository of free unplugged parallel & distributed computing (PDC) activities"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/activities/"
    name = "All Activities"
    weight = 3

[[menu.main]]
    url = "/cs2013/"
    name = "CS2013 View"
    weight = 4

[[menu.main]]
    url = "/tcpp/"
    name = "TCPP View"
    weight = 4

[[menu.main]]
    url = "/courses/"
    name = "Course View"
    weight = 4

[[menu.main]]
    url = "/accessibility/"
    name = "Accesibility View"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/suzannejmatthews/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

