baseURL = "https://www.pdcunplugged.org"
languageCode = "en-us"
title = "PDC Unplugged"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-155045117-1"
publishDir = "docs"

[taxonomies]
    tag="tags"
    course = "courses"
    sense = "senses"
    tcpp = "tcpp"
    cs2013 = "cs2013"
    cs2013detail = "cs2013details"
    tcppdetail = "tcppdetails"

[params]
    author = "Suzanne J. Matthews (CSinParallel)"
    description = "A repository of free unplugged parallel & distributed computing (PDC) activities"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/contribute/"
    name = "Contribute"
    weight = 2

[[menu.main]]
    url = "/activities/"
    name = "All Activities"
    weight = 3

[[menu.main]]
    url = "/cs2013-overview/"
    name = "CS2013 View"
    weight = 4

[[menu.main]]
    url = "/tcpp-overview/"
    name = "TCPP View"
    weight = 4

[[menu.main]]
    url = "/course-overview/"
    name = "Course View"
    weight = 4

[[menu.main]]
    url = "/senses/"
    name = "Accesibility View"
    weight = 4


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "http://suzannejmatthews.com/"
    name = "id-card"
    weight = 1

[[menu.icon]]
    url = "https://github.com/suzannejmatthews/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/suzannejmatthews/"
    name = "linkedin"
    weight = 4

